name: ssdt
channels:
  - pytorch
  - xformers/label/dev
  - nvidia/label/cuda-11.6.2
  - huggingface
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - requests
  - cuda-toolkit
  - pytorch
  - torchvision
  - pytorch-cuda=11.6
  - pillow
  - transformers
  - omegaconf
  - pytorch-lightning
  - numpy
  - tqdm
  - click
  - ftfy
  - accelerate
  - psutil
  - xformers=0.0.15.dev343+git.1b1fd8a
  - wandb
  - pip:
      - bitsandbytes~=0.35
      - torch-ema==0.3
      - git+https://github.com/CCRcmcpe/diffusers.git